/**
 * Generate academy video mission replays from real engine play (MCTS / heuristic).
 *
 * Ep09 — Fleet Draft midgame skirmish (MCTS)
 * Ep10 — Infiltrator warp + Target Lock crawl (Heuristic AI)
 * Ep11 — Lockout (winnerReason=no-moves); AI hunt then engine-composed fallback
 *
 * Usage (cwd = packages/subspace-lattice):
 *   bash scripts/academy-mission-generate.sh --write
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { SubspaceLatticeEngine } from '../game-engine';
import { applyAgentMove, isEmpAgentMove } from '../ai/agent';
import { HeuristicAi } from '../ai/heuristic-ai';
import { MctsAi } from '../ai/mcts-ai';
import { RandomLegalAgent } from '../ai/random-legal-agent';
import { createSeededRng } from '../ai/rng';
import { PieceType } from '../interfaces/pieceType';
import { PlayerColor } from '../interfaces/playerColor';
import type { GameState } from '../interfaces/gameState';
import {
  resolveFleetLobbyRules,
  resolveRulesConfig,
  type RulesConfig,
} from '../rules/rules-config';
import { playMatch, type MatchResult, type ReplayPly } from './match-runner';

const REACT_DATA = resolve(
  process.cwd(),
  '../subspace-lattice-react/src/tutorial/data',
);

interface AcademyMove {
  seat: string;
  pieceId: string;
  from: { x: number; y: number };
  to: { x: number; y: number };
  captured?: string;
  pieceType: string;
}

interface AnnotatedReplay {
  id: string;
  seed: number;
  sims: number;
  plies: number;
  winner?: string;
  winnerReason?: string;
  rulesLabel: string;
  notes: string[];
  highlights?: Record<string, number[]>;
  moves: AcademyMove[];
}

function toAcademyMoves(
  rules: RulesConfig,
  replay: ReplayPly[],
  startState?: GameState,
): AcademyMove[] {
  const engine = startState
    ? SubspaceLatticeEngine.fromState(startState, rules)
    : new SubspaceLatticeEngine({ rules });
  const moves: AcademyMove[] = [];
  for (const ply of replay) {
    const piece = engine.getState().pieces[ply.pieceId];
    if (!piece) {
      throw new Error(`Missing piece ${ply.pieceId} while converting replay`);
    }
    const from = { ...piece.position };
    const target = engine.getPieceAt(ply.to);
    if (!engine.movePiece(ply.pieceId, ply.to)) {
      throw new Error(
        `Illegal while converting ${ply.pieceId} -> (${ply.to.x},${ply.to.y})`,
      );
    }
    const move: AcademyMove = {
      seat: ply.player === PlayerColor.White ? 'WHITE' : 'BLACK',
      pieceId: ply.pieceId,
      from,
      to: { ...ply.to },
      pieceType: String(ply.moverType),
    };
    if (target) move.captured = target.id;
    moves.push(move);
  }
  return moves;
}

function chebyshev(
  a: { x: number; y: number },
  b: { x: number; y: number },
): number {
  return Math.max(Math.abs(a.x - b.x), Math.abs(a.y - b.y));
}

function analyzeInfiltratorMoments(
  rules: RulesConfig,
  replay: ReplayPly[],
): { warps: number[]; lockedCrawls: number[]; captures: number[] } {
  const engine = new SubspaceLatticeEngine({ rules });
  const warps: number[] = [];
  const lockedCrawls: number[] = [];
  const captures: number[] = [];
  for (let i = 0; i < replay.length; i++) {
    const ply = replay[i]!;
    const piece = engine.getState().pieces[ply.pieceId];
    if (!piece) break;
    const from = { ...piece.position };
    const detectedBefore = engine.isPieceDetected(piece);
    const dist = chebyshev(from, ply.to);
    engine.movePiece(ply.pieceId, ply.to);
    if (ply.moverType !== PieceType.Infiltrator) continue;
    const plyNum = i + 1;
    if (ply.capturedType) captures.push(plyNum);
    if (dist > 1 && !detectedBefore) warps.push(plyNum);
    if (dist === 1 && detectedBefore) lockedCrawls.push(plyNum);
  }
  return { warps, lockedCrawls, captures };
}

function writeReplay(fileBase: string, data: AnnotatedReplay): string {
  mkdirSync(REACT_DATA, { recursive: true });
  // Match existing mission-*-replay.ts style (JSON import needs resolveJsonModule).
  const outPath = resolve(REACT_DATA, `${fileBase}.ts`);
  const body = `/* Pre-calculated academy AI mission replay. Generated by academy-mission-generate; do not hand-edit moves. */
import type { MissionReplayMove } from '../walkthrough-narrate';

const replay: {
  id: string;
  seed: number;
  sims: number;
  plies: number;
  winner?: string;
  winnerReason?: string;
  rulesLabel: string;
  notes: string[];
  highlights?: Record<string, number[]>;
  moves: MissionReplayMove[];
} = ${JSON.stringify(data, null, 2)};

export default replay;
`;
  writeFileSync(outPath, body, 'utf8');
  return outPath;
}

function mctsMatch(
  rules: RulesConfig,
  seed: number,
  sims: number,
  maxPlies: number,
): MatchResult {
  return playMatch(
    new MctsAi({ simulations: sims, rng: createSeededRng(seed) }),
    new MctsAi({ simulations: sims, rng: createSeededRng(seed + 9973) }),
    { rules, maxPlies },
  );
}

/** Prefers moves that leave the opponent with fewer legal replies; takes Lockout instantly. */
class MobilityPressureAgent {
  readonly name = 'mobility-pressure';
  constructor(private readonly rng: () => number = Math.random) {}

  chooseMove(engine: SubspaceLatticeEngine) {
    const legal = engine.listLegalMoves();
    if (legal.length === 0) return null;
    // Cap probes for speed; always include captures first.
    const captures = legal.filter((m) => engine.getPieceAt(m.to));
    const rest = legal.filter((m) => !engine.getPieceAt(m.to));
    const sample = [...captures, ...rest].slice(0, 14);
    let best = sample[0]!;
    let bestScore = Number.POSITIVE_INFINITY;
    for (const move of sample) {
      const probe = engine.clone();
      if (!probe.movePiece(move.pieceId, move.to)) continue;
      if (probe.getState().winnerReason === 'no-moves') {
        return { pieceId: move.pieceId, to: move.to };
      }
      if (probe.getState().winner) {
        if (-1 < bestScore) {
          bestScore = -1;
          best = move;
        }
        continue;
      }
      const reply = probe.listLegalMoves().length;
      const jitter = this.rng() * 0.01;
      if (reply + jitter < bestScore) {
        bestScore = reply + jitter;
        best = move;
      }
    }
    return { pieceId: best.pieceId, to: best.to };
  }
}

/**
 * Lockout is rare in free play (packed surfaces always keep an ortho step).
 * Record a mobility-pressure game and flag the ply where Black’s reply count
 * was minimized — the teaching “one squeeze from Lockout” position.
 * If a true no-moves finish appears, prefer that.
 */
function composeLockoutDemo(_rules: RulesConfig): {
  result: MatchResult;
  seed: number;
  nearLockoutPly?: number;
  nearLockoutReplies?: number;
} {
  const deferred = resolveRulesConfig('hybrid-fleet', {
    sectorActivationPly: 10_000,
    sectorHoldPlies: 999,
  });
  let best: {
    result: MatchResult;
    seed: number;
    nearPly: number;
    nearReplies: number;
  } | null = null;

  for (let i = 0; i < 16; i++) {
    const seed = 25000 + i * 19;
    const white = new MobilityPressureAgent(createSeededRng(seed));
    const black = new RandomLegalAgent(createSeededRng(seed + 4));
    const engine = new SubspaceLatticeEngine({ rules: deferred });
    const replay: MatchResult['replay'] = [];
    let nearPly = 0;
    let nearReplies = Number.POSITIVE_INFINITY;

    for (let plies = 0; plies < 100; plies++) {
      const state = engine.getState();
      if (state.winner) break;
      if (state.currentPlayer === PlayerColor.Black) {
        const n = engine.listLegalMoves(PlayerColor.Black).length;
        if (n < nearReplies) {
          nearReplies = n;
          nearPly = plies;
        }
      }
      const agent =
        state.currentPlayer === PlayerColor.White ? white : black;
      const choice = agent.chooseMove(engine);
      if (!choice) {
        const winner =
          state.currentPlayer === PlayerColor.White
            ? PlayerColor.Black
            : PlayerColor.White;
        const result: MatchResult = {
          winner,
          winnerReason: 'no-moves',
          plies: replay.length,
          truncated: false,
          replay,
          rulesVersion: deferred.version,
          capturesByMoverType: {},
          infiltratorCaptures: 0,
          spoolAnnounces: 0,
          spoolFailures: 0,
        };
        console.log(
          JSON.stringify({
            hunt: 'ep11-true-lockout',
            seed,
            plies: result.plies,
          }),
        );
        return { result, seed };
      }
      const player = state.currentPlayer;
      if (isEmpAgentMove(choice)) {
        applyAgentMove(engine, choice);
        const hub = Object.values(engine.getState().pieces).find(
          (p) => p.owner === player && p.type === PieceType.CommandHub,
        );
        replay.push({
          pieceId: hub?.id ?? 'emp',
          to: hub ? { ...hub.position } : { x: 0, y: 0 },
          player,
          moverType: PieceType.CommandHub,
          empFired: true,
        });
        continue;
      }
      const piece = engine.getState().pieces[choice.pieceId]!;
      applyAgentMove(engine, choice);
      const info = engine.getLastMoveInfo();
      replay.push({
        pieceId: choice.pieceId,
        to: choice.to,
        player,
        moverType: info?.moverType ?? piece.type,
        capturedType: info?.capturedType,
      });
    }

    const final = engine.getState();
    const result: MatchResult = {
      winner: final.winner,
      winnerReason: final.winnerReason,
      plies: replay.length,
      truncated: !final.winner,
      replay,
      rulesVersion: deferred.version,
      capturesByMoverType: {},
      infiltratorCaptures: 0,
      spoolAnnounces: 0,
      spoolFailures: 0,
    };
    console.log(
      JSON.stringify({
        hunt: 'ep11-pressure',
        seed,
        plies: result.plies,
        reason: result.winnerReason,
        nearPly,
        nearReplies,
      }),
    );
    if (
      !best ||
      nearReplies < best.nearReplies ||
      (nearReplies === best.nearReplies && result.plies > best.result.plies)
    ) {
      best = { result, seed, nearPly, nearReplies };
    }
  }

  if (!best) throw new Error('composeLockoutDemo: no games');
  return {
    result: best.result,
    seed: best.seed,
    nearLockoutPly: best.nearPly,
    nearLockoutReplies: best.nearReplies,
  };
}

function main(): void {
  const write = process.argv.includes('--write');
  const fleetRules = resolveFleetLobbyRules({
    heavyWingPreset: 'fleet-draft',
  });
  const standardFleet = resolveRulesConfig('hybrid-fleet');

  console.log(
    JSON.stringify(
      { write, outDir: REACT_DATA, draft: fleetRules.heavyUnitDraft },
      null,
      2,
    ),
  );

  // --- Ep09 ---
  // Single known-good seed (prior hunt: heavy piece activity through ply 56).
  const skirmishSeed = 9200;
  const skirmishResult = mctsMatch(fleetRules, skirmishSeed, 28, 44);
  console.log(
    JSON.stringify({
      hunt: 'ep09',
      seed: skirmishSeed,
      plies: skirmishResult.plies,
      reason: skirmishResult.winnerReason,
      heavy: skirmishResult.replay.filter(
        (p) =>
          p.moverType === PieceType.Refractor ||
          p.moverType === PieceType.Carrier,
      ).length,
    }),
  );
  const bestSkirmish = { seed: skirmishSeed, result: skirmishResult };
  const skirmishKeep = Math.min(40, bestSkirmish.result.replay.length);
  const skirmishMoves = toAcademyMoves(
    fleetRules,
    bestSkirmish.result.replay.slice(0, skirmishKeep),
  );
  const skirmishDoc: AnnotatedReplay = {
    id: 'mission-ai-fleet-skirmish',
    seed: bestSkirmish.seed,
    sims: 28,
    plies: skirmishMoves.length,
    winner: bestSkirmish.result.winner,
    winnerReason: bestSkirmish.result.winnerReason,
    rulesLabel: 'hybrid-fleet + fleet-draft',
    notes: [
      `MCTS(28) vs MCTS(28), seed ${bestSkirmish.seed}`,
      `First ${skirmishMoves.length} plies — Fleet Draft midgame teaching window`,
    ],
    moves: skirmishMoves,
  };

  // --- Ep10 ---
  let bestInf: {
    seed: number;
    result: MatchResult;
    moments: ReturnType<typeof analyzeInfiltratorMoments>;
    quality: number;
  } | null = null;
  for (let i = 0; i < 80; i++) {
    const seed = 12100 + i * 17;
    const result = playMatch(
      new HeuristicAi(createSeededRng(seed)),
      new HeuristicAi(createSeededRng(seed + 3)),
      { rules: standardFleet, maxPlies: 90 },
    );
    const moments = analyzeInfiltratorMoments(standardFleet, result.replay);
    const quality =
      moments.warps.length * 10 +
      moments.lockedCrawls.length * 14 +
      moments.captures.length * 8 +
      (moments.warps.length && moments.lockedCrawls.length ? 50 : 0);
    if (quality <= 0) continue;
    console.log(
      JSON.stringify({
        hunt: 'ep10',
        seed,
        plies: result.plies,
        reason: result.winnerReason,
        ...moments,
        quality,
      }),
    );
    if (!bestInf || quality > bestInf.quality) {
      bestInf = { seed, result, moments, quality };
    }
    if (moments.warps.length && moments.lockedCrawls.length) break;
  }
  if (!bestInf?.moments.warps.length) {
    throw new Error('ep10: no infiltrator warp found');
  }

  const lastInteresting = Math.max(
    ...bestInf.moments.warps,
    ...(bestInf.moments.lockedCrawls.length
      ? bestInf.moments.lockedCrawls
      : [0]),
    ...(bestInf.moments.captures.length ? bestInf.moments.captures : [0]),
  );
  const infKeep = Math.min(
    bestInf.result.replay.length,
    Math.max(lastInteresting + 3, 20),
  );
  const infMoves = toAcademyMoves(
    standardFleet,
    bestInf.result.replay.slice(0, infKeep),
  );
  const infDoc: AnnotatedReplay = {
    id: 'mission-ai-infiltrator',
    seed: bestInf.seed,
    sims: 0,
    plies: infMoves.length,
    winner: bestInf.result.winner,
    winnerReason: bestInf.result.winnerReason,
    rulesLabel: 'hybrid-fleet (standard beams)',
    notes: [
      `Heuristic AI vs Heuristic AI, seed ${bestInf.seed}`,
      `Warps @ ${bestInf.moments.warps.join(', ')}`,
      `Locked crawls @ ${bestInf.moments.lockedCrawls.join(', ') || '—'}`,
      `Infiltrator captures @ ${bestInf.moments.captures.join(', ') || '—'}`,
    ],
    highlights: {
      warps: bestInf.moments.warps,
      lockedCrawls: bestInf.moments.lockedCrawls,
      captures: bestInf.moments.captures,
    },
    moves: infMoves,
  };

  // Lockout (winnerReason=no-moves) is rare in free play; record a
  // mobility-pressure squeeze and teach the engine rule from near-zero replies.
  const composed = composeLockoutDemo(standardFleet);
  const lockout = {
    seed: composed.seed,
    result: composed.result,
    nearLockoutPly: composed.nearLockoutPly,
    nearLockoutReplies: composed.nearLockoutReplies,
  };
  console.log(
    JSON.stringify({
      hunt: 'ep11-lockout',
      plies: lockout.result.plies,
      reason: lockout.result.winnerReason,
      winner: lockout.result.winner,
      nearLockoutPly: lockout.nearLockoutPly,
      nearLockoutReplies: lockout.nearLockoutReplies,
    }),
  );

  const lockRules = resolveRulesConfig('hybrid-fleet', {
    sectorActivationPly: 10_000,
    sectorHoldPlies: 999,
  });
  const lockMoves = toAcademyMoves(lockRules, lockout.result.replay);
  /** Board ply when Black faces the fewest replies (moves already played). */
  const squeezePly = lockout.nearLockoutPly ?? Math.max(0, lockMoves.length - 8);
  const focusFrom = Math.max(1, squeezePly - 15);
  const trueLockout = lockout.result.winnerReason === 'no-moves';
  const lockDoc: AnnotatedReplay = {
    id: 'mission-ai-lockout',
    seed: lockout.seed,
    sims: 0,
    plies: lockMoves.length,
    winner: lockout.result.winner,
    winnerReason: lockout.result.winnerReason,
    rulesLabel: 'hybrid-fleet (clock deferred; mobility-pressure AI)',
    notes: [
      trueLockout
        ? 'True Lockout: winnerReason=no-moves — immobility is defeat, not stalemate'
        : `Near-Lockout squeeze: after ply ${squeezePly}, Black has ${lockout.nearLockoutReplies ?? '?'} legal replies (engine awards no-moves at zero — immobility is defeat)`,
      `Mobility-pressure AI vs Random, seed ${lockout.seed}`,
      `Teaching focus: plies ${focusFrom}–${lockMoves.length}`,
    ],
    highlights: {
      focusFrom: [focusFrom],
      squeeze: [squeezePly],
      terminal: [lockMoves.length],
      nearReplies: lockout.nearLockoutReplies != null
        ? [lockout.nearLockoutReplies]
        : [],
    },
    moves: lockMoves,
  };

  const summary = {
    ep09: {
      id: skirmishDoc.id,
      seed: skirmishDoc.seed,
      plies: skirmishDoc.plies,
    },
    ep10: {
      id: infDoc.id,
      seed: infDoc.seed,
      plies: infDoc.plies,
      highlights: infDoc.highlights,
    },
    ep11: {
      id: lockDoc.id,
      seed: lockDoc.seed,
      plies: lockDoc.plies,
      winnerReason: lockDoc.winnerReason,
      nearLockoutPly: lockout.nearLockoutPly,
      nearLockoutReplies: lockout.nearLockoutReplies,
    },
  };
  console.log(JSON.stringify({ summary }, null, 2));

  if (write) {
    const written = [
      writeReplay('mission-ai-fleet-skirmish-replay', skirmishDoc),
      writeReplay('mission-ai-infiltrator-replay', infDoc),
      writeReplay('mission-ai-lockout-replay', lockDoc),
    ];
    console.log(JSON.stringify({ written }, null, 2));
  } else {
    console.log('Dry run only. Pass --write to emit replay JSON.');
  }
}

main();
