import { useMemo, useRef } from 'react';
import {
  CellType,
  PieceType,
  PlayerColor,
  SubspaceLatticeEngine,
  type Piece,
  type RulesVersion,
} from '@subspace-lattice/core';

const CELL = 58;
const MARGIN = 72;
/** Board's top edge: title (y≈36) + subtitle (y≈58) band, then the column
 * label strip — kept separate from MARGIN so the header never collides
 * with the grid labels. */
const TOP = 96;
const BOARD = CELL * 11;
const WIDTH = BOARD + MARGIN * 2;
/** Legend sits 34px under the board with three 24px lines; +28px padding. */
const HEIGHT = TOP + BOARD + 110;

/** Same chess-style glyphs as `Board` / RulesDialog for rules-manual parity. */
function pieceGlyph(type: PieceType, owner: PlayerColor): string {
  const white = owner === PlayerColor.White;
  switch (type) {
    case PieceType.CommandHub:
      return white ? '♔' : '♚';
    case PieceType.Escort:
      return white ? '♙' : '♟';
    case PieceType.Infiltrator:
      return white ? '♘' : '♞';
    case PieceType.Beam:
      return white ? '♖' : '♜';
    default:
      return '?';
  }
}

const PIECE_SHORT: Record<PieceType, string> = {
  [PieceType.CommandHub]: 'H',
  [PieceType.Escort]: 'E',
  [PieceType.Infiltrator]: 'I',
  [PieceType.Beam]: 'B',
};

function pieceName(piece: Piece): string {
  const side = piece.owner === PlayerColor.White ? 'White' : 'Black';
  const name = {
    [PieceType.CommandHub]: 'Command Hub',
    [PieceType.Escort]: 'Escort',
    [PieceType.Infiltrator]: 'Infiltrator',
    [PieceType.Beam]: 'Beam',
  }[piece.type];
  return `${side} ${name} at (${piece.position.x}, ${piece.position.y})`;
}

export interface SetupDiagramProps {
  rulesVersion?: RulesVersion;
  showSensorNets?: boolean;
  title?: string;
}

/**
 * Self-contained SVG generated from the engine's canonical initial state.
 *
 * Unlike `Board`'s CSS-grid fill order (which visually runs y left→right),
 * this diagram maps engine x→horizontal and y→vertical with White (y=0) at
 * the bottom — the natural rules-manual orientation.
 */
export function SetupDiagram({
  rulesVersion = 'hybrid',
  showSensorNets = true,
  title = 'Subspace Lattice — Initial Fleet Deployment',
}: SetupDiagramProps) {
  const model = useMemo(() => {
    const engine = new SubspaceLatticeEngine({ rulesVersion });
    return {
      engine,
      state: engine.getState(),
      whiteNet: engine.getSensorNetSet(PlayerColor.White),
      blackNet: engine.getSensorNetSet(PlayerColor.Black),
    };
  }, [rulesVersion]);

  const boardSize = model.state.boardSize;
  const displayY = (y: number) => boardSize - 1 - y;

  return (
    <svg
      id="subspace-lattice-setup-diagram"
      xmlns="http://www.w3.org/2000/svg"
      viewBox={`0 0 ${WIDTH} ${HEIGHT}`}
      role="img"
      aria-labelledby="setup-diagram-title setup-diagram-description"
      style={{ width: 'min(100%, 900px)', height: 'auto' }}
    >
      <title id="setup-diagram-title">{title}</title>
      <desc id="setup-diagram-description">
        Canonical eleven by eleven initial setup generated by the game engine.
        White begins at y zero along the bottom; Black begins at y ten along
        the top. The center gravity well is at coordinate five, five.
      </desc>
      <style>{`
        .sd-title { font: 700 25px system-ui, sans-serif; fill: #eaf4ff; }
        .sd-subtitle { font: 14px system-ui, sans-serif; fill: #98afc6; }
        .sd-coordinate { font: 12px ui-monospace, monospace; fill: #8ea6bc; }
        .sd-cell { stroke: #36506a; stroke-width: 1; }
        .sd-piece-label { font: 700 17px system-ui, sans-serif; text-anchor: middle; dominant-baseline: central; }
        .sd-piece-glyph { font: 15px system-ui, sans-serif; text-anchor: middle; dominant-baseline: central; opacity: .35; }
        .sd-legend { font: 13px system-ui, sans-serif; fill: #bcd0e1; }
      `}</style>

      <rect width={WIDTH} height={HEIGHT} rx="18" fill="#07131f" />
      <text x={MARGIN} y="36" className="sd-title">
        {title}
      </text>
      <text x={MARGIN} y="58" className="sd-subtitle">
        Rules: {rulesVersion} · White moves first · coordinates match the engine
      </text>

      {model.state.cells.map((cell) => {
        const { x, y } = cell.coordinate;
        const key = `${x},${y}`;
        const inWhite = showSensorNets && model.whiteNet.has(key);
        const inBlack = showSensorNets && model.blackNet.has(key);
        const fill =
          cell.type === CellType.GravityWell
            ? '#12151b'
            : inWhite && inBlack
              ? '#665173'
              : inWhite
                ? '#315b7a'
                : inBlack
                  ? '#713b4a'
                  : (x + y) % 2 === 0
                    ? '#13283a'
                    : '#102131';
        return (
          <g key={key}>
            <rect
              className="sd-cell"
              x={MARGIN + x * CELL}
              y={TOP + displayY(y) * CELL}
              width={CELL}
              height={CELL}
              fill={fill}
            />
            {cell.type === CellType.GravityWell && (
              <>
                <circle
                  cx={MARGIN + x * CELL + CELL / 2}
                  cy={TOP + displayY(y) * CELL + CELL / 2}
                  r="19"
                  fill="#020407"
                  stroke="#8b68aa"
                  strokeWidth="3"
                />
                <circle
                  cx={MARGIN + x * CELL + CELL / 2}
                  cy={TOP + displayY(y) * CELL + CELL / 2}
                  r="8"
                  fill="#8b68aa"
                  opacity=".7"
                />
              </>
            )}
          </g>
        );
      })}

      {Array.from({ length: boardSize }, (_, i) => (
        <g key={`coordinate-${i}`}>
          <text
            x={MARGIN + i * CELL + CELL / 2}
            y={TOP - 11}
            textAnchor="middle"
            className="sd-coordinate"
          >
            {i}
          </text>
          <text
            x={MARGIN - 18}
            y={TOP + displayY(i) * CELL + CELL / 2}
            textAnchor="middle"
            dominantBaseline="central"
            className="sd-coordinate"
          >
            {i}
          </text>
        </g>
      ))}

      {Object.values(model.state.pieces).map((piece) => {
        const cx = MARGIN + piece.position.x * CELL + CELL / 2;
        const cy = TOP + displayY(piece.position.y) * CELL + CELL / 2;
        const white = piece.owner === PlayerColor.White;
        return (
          <g key={piece.id}>
            <title>{pieceName(piece)}</title>
            <circle
              cx={cx}
              cy={cy}
              r="22"
              fill={white ? '#e8f4ff' : '#17202a'}
              stroke={white ? '#5db7ef' : '#ef6c86'}
              strokeWidth="3"
            />
            <text
              x={cx}
              y={cy - 8}
              className="sd-piece-glyph"
              fill={white ? '#123149' : '#f5dce1'}
            >
              {pieceGlyph(piece.type, piece.owner)}
            </text>
            <text
              x={cx}
              y={cy + 7}
              className="sd-piece-label"
              fill={white ? '#10273a' : '#f4e8eb'}
            >
              {PIECE_SHORT[piece.type]}
            </text>
          </g>
        );
      })}

      <g transform={`translate(${MARGIN}, ${TOP + BOARD + 34})`}>
        <text className="sd-legend" x="0" y="0">
          H/♔ Command Hub · E/♙ Escort · I/♘ Infiltrator · B/♖ Beam
        </text>
        <text className="sd-legend" x="0" y="24">
          Blue: White Sensor Net · Red: Black Sensor Net · Purple: Gravity Well
        </text>
        <text className="sd-legend" x="0" y="48">
          White deployment edge (y=0) is shown at bottom
        </text>
      </g>
    </svg>
  );
}

export function SetupDiagramHarness() {
  const containerRef = useRef<HTMLDivElement>(null);

  const downloadSvg = () => {
    const svg = containerRef.current?.querySelector('svg');
    if (!svg) return;
    const source = new XMLSerializer().serializeToString(svg);
    const blob = new Blob([source], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement('a');
    anchor.href = url;
    anchor.download = 'subspace-lattice-initial-setup.svg';
    anchor.click();
    URL.revokeObjectURL(url);
  };

  return (
    <main
      ref={containerRef}
      style={{
        minHeight: '100vh',
        background: '#050d15',
        padding: '24px',
        color: '#eaf4ff',
        fontFamily: 'system-ui, sans-serif',
      }}
    >
      <div style={{ maxWidth: 900, margin: '0 auto' }}>
        <SetupDiagram />
        <p>
          This diagram is generated from the engine’s initial state. Save it
          directly or capture it at any viewport size.
        </p>
        <button type="button" onClick={downloadSvg}>
          Download SVG
        </button>
      </div>
    </main>
  );
}
