/* Pre-calculated academy AI mission replay. Generated by academy-mission-generate; do not hand-edit moves. */
import type { MissionReplayMove } from '../walkthrough-narrate';

const replay: {
  id: string;
  seed: number;
  sims: number;
  plies: number;
  winner?: string;
  winnerReason?: string;
  rulesLabel: string;
  notes: string[];
  highlights?: Record<string, number[]>;
  moves: MissionReplayMove[];
} = {
  "id": "mission-ai-fleet-skirmish",
  "seed": 9200,
  "sims": 28,
  "plies": 40,
  "rulesLabel": "hybrid-fleet + fleet-draft",
  "notes": [
    "MCTS(28) vs MCTS(28), seed 9200",
    "First 40 plies — Fleet Draft midgame teaching window"
  ],
  "moves": [
    {
      "seat": "WHITE",
      "pieceId": "w-i2",
      "from": {
        "x": 8,
        "y": 0
      },
      "to": {
        "x": 6,
        "y": 3
      },
      "pieceType": "INFILTRATOR"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-i1",
      "from": {
        "x": 2,
        "y": 10
      },
      "to": {
        "x": 1,
        "y": 2
      },
      "pieceType": "INFILTRATOR"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-i1",
      "from": {
        "x": 2,
        "y": 0
      },
      "to": {
        "x": 1,
        "y": 2
      },
      "pieceType": "INFILTRATOR",
      "captured": "b-i1"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-i2",
      "from": {
        "x": 8,
        "y": 10
      },
      "to": {
        "x": 1,
        "y": 2
      },
      "pieceType": "INFILTRATOR",
      "captured": "w-i1"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-i2",
      "from": {
        "x": 6,
        "y": 3
      },
      "to": {
        "x": 1,
        "y": 2
      },
      "pieceType": "INFILTRATOR",
      "captured": "b-i2"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-ch",
      "from": {
        "x": 5,
        "y": 10
      },
      "to": {
        "x": 6,
        "y": 9
      },
      "pieceType": "COMMAND_HUB"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-i2",
      "from": {
        "x": 1,
        "y": 2
      },
      "to": {
        "x": 2,
        "y": 2
      },
      "pieceType": "INFILTRATOR"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-e3",
      "from": {
        "x": 5,
        "y": 9
      },
      "to": {
        "x": 5,
        "y": 10
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-i2",
      "from": {
        "x": 2,
        "y": 2
      },
      "to": {
        "x": 1,
        "y": 2
      },
      "pieceType": "INFILTRATOR"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-h2",
      "from": {
        "x": 7,
        "y": 10
      },
      "to": {
        "x": 9,
        "y": 8
      },
      "pieceType": "CARRIER"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-h2",
      "from": {
        "x": 7,
        "y": 0
      },
      "to": {
        "x": 5,
        "y": 2
      },
      "pieceType": "CARRIER"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-ch",
      "from": {
        "x": 6,
        "y": 9
      },
      "to": {
        "x": 6,
        "y": 8
      },
      "pieceType": "COMMAND_HUB"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-i2",
      "from": {
        "x": 1,
        "y": 2
      },
      "to": {
        "x": 7,
        "y": 0
      },
      "pieceType": "INFILTRATOR"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-e2",
      "from": {
        "x": 6,
        "y": 10
      },
      "to": {
        "x": 7,
        "y": 10
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-h2",
      "from": {
        "x": 5,
        "y": 2
      },
      "to": {
        "x": 4,
        "y": 1
      },
      "pieceType": "CARRIER"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-h1",
      "from": {
        "x": 3,
        "y": 10
      },
      "to": {
        "x": 5,
        "y": 8
      },
      "pieceType": "REFRACTOR"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-i2",
      "from": {
        "x": 7,
        "y": 0
      },
      "to": {
        "x": 10,
        "y": 5
      },
      "pieceType": "INFILTRATOR"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-ch",
      "from": {
        "x": 6,
        "y": 8
      },
      "to": {
        "x": 7,
        "y": 7
      },
      "pieceType": "COMMAND_HUB"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-e4",
      "from": {
        "x": 5,
        "y": 3
      },
      "to": {
        "x": 5,
        "y": 2
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-ch",
      "from": {
        "x": 7,
        "y": 7
      },
      "to": {
        "x": 6,
        "y": 6
      },
      "pieceType": "COMMAND_HUB"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-i2",
      "from": {
        "x": 10,
        "y": 5
      },
      "to": {
        "x": 0,
        "y": 0
      },
      "pieceType": "INFILTRATOR"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-ch",
      "from": {
        "x": 6,
        "y": 6
      },
      "to": {
        "x": 5,
        "y": 7
      },
      "pieceType": "COMMAND_HUB"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-i2",
      "from": {
        "x": 0,
        "y": 0
      },
      "to": {
        "x": 9,
        "y": 8
      },
      "pieceType": "INFILTRATOR",
      "captured": "b-h2"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-ch",
      "from": {
        "x": 5,
        "y": 7
      },
      "to": {
        "x": 4,
        "y": 8
      },
      "pieceType": "COMMAND_HUB"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-i2",
      "from": {
        "x": 9,
        "y": 8
      },
      "to": {
        "x": 7,
        "y": 3
      },
      "pieceType": "INFILTRATOR"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-ch",
      "from": {
        "x": 4,
        "y": 8
      },
      "to": {
        "x": 4,
        "y": 7
      },
      "pieceType": "COMMAND_HUB"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-i2",
      "from": {
        "x": 7,
        "y": 3
      },
      "to": {
        "x": 2,
        "y": 0
      },
      "pieceType": "INFILTRATOR"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-e2",
      "from": {
        "x": 7,
        "y": 10
      },
      "to": {
        "x": 7,
        "y": 9
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-h2",
      "from": {
        "x": 4,
        "y": 1
      },
      "to": {
        "x": 3,
        "y": 1
      },
      "pieceType": "CARRIER"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-ch",
      "from": {
        "x": 4,
        "y": 7
      },
      "to": {
        "x": 5,
        "y": 7
      },
      "pieceType": "COMMAND_HUB"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-i2",
      "from": {
        "x": 2,
        "y": 0
      },
      "to": {
        "x": 9,
        "y": 0
      },
      "pieceType": "INFILTRATOR"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-e1",
      "from": {
        "x": 4,
        "y": 10
      },
      "to": {
        "x": 3,
        "y": 10
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-i2",
      "from": {
        "x": 9,
        "y": 0
      },
      "to": {
        "x": 9,
        "y": 5
      },
      "pieceType": "INFILTRATOR"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-ch",
      "from": {
        "x": 5,
        "y": 7
      },
      "to": {
        "x": 5,
        "y": 6
      },
      "pieceType": "COMMAND_HUB"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-i2",
      "from": {
        "x": 9,
        "y": 5
      },
      "to": {
        "x": 10,
        "y": 3
      },
      "pieceType": "INFILTRATOR"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-h1",
      "from": {
        "x": 5,
        "y": 8
      },
      "to": {
        "x": 6,
        "y": 9
      },
      "pieceType": "REFRACTOR"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-i2",
      "from": {
        "x": 10,
        "y": 3
      },
      "to": {
        "x": 5,
        "y": 10
      },
      "pieceType": "INFILTRATOR",
      "captured": "b-e3"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-e1",
      "from": {
        "x": 3,
        "y": 10
      },
      "to": {
        "x": 2,
        "y": 10
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-i2",
      "from": {
        "x": 5,
        "y": 10
      },
      "to": {
        "x": 2,
        "y": 10
      },
      "pieceType": "INFILTRATOR",
      "captured": "b-e1"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-ch",
      "from": {
        "x": 5,
        "y": 6
      },
      "to": {
        "x": 5,
        "y": 7
      },
      "pieceType": "COMMAND_HUB"
    }
  ]
};

export default replay;
