/* Pre-calculated academy AI mission replay. Generated by academy-mission-generate; do not hand-edit moves. */
import type { MissionReplayMove } from '../walkthrough-narrate';

const replay: {
  id: string;
  seed: number;
  sims: number;
  plies: number;
  winner?: string;
  winnerReason?: string;
  rulesLabel: string;
  notes: string[];
  highlights?: Record<string, number[]>;
  moves: MissionReplayMove[];
} = {
  "id": "mission-ai-infiltrator",
  "seed": 12100,
  "sims": 0,
  "plies": 49,
  "rulesLabel": "hybrid-fleet (standard beams)",
  "notes": [
    "Heuristic AI vs Heuristic AI, seed 12100",
    "Warps @ 1, 2, 3, 4, 6, 18, 20",
    "Locked crawls @ 46",
    "Infiltrator captures @ 2, 3, 4, 18, 20, 46"
  ],
  "highlights": {
    "warps": [
      1,
      2,
      3,
      4,
      6,
      18,
      20
    ],
    "lockedCrawls": [
      46
    ],
    "captures": [
      2,
      3,
      4,
      18,
      20,
      46
    ]
  },
  "moves": [
    {
      "seat": "WHITE",
      "pieceId": "w-i1",
      "from": {
        "x": 3,
        "y": 0
      },
      "to": {
        "x": 9,
        "y": 10
      },
      "pieceType": "INFILTRATOR"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-i1",
      "from": {
        "x": 3,
        "y": 10
      },
      "to": {
        "x": 9,
        "y": 10
      },
      "pieceType": "INFILTRATOR",
      "captured": "w-i1"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-i2",
      "from": {
        "x": 7,
        "y": 0
      },
      "to": {
        "x": 9,
        "y": 10
      },
      "pieceType": "INFILTRATOR",
      "captured": "b-i1"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-i2",
      "from": {
        "x": 7,
        "y": 10
      },
      "to": {
        "x": 9,
        "y": 10
      },
      "pieceType": "INFILTRATOR",
      "captured": "w-i2"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-h1",
      "from": {
        "x": 2,
        "y": 0
      },
      "to": {
        "x": 2,
        "y": 3
      },
      "pieceType": "BEAM"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-i2",
      "from": {
        "x": 9,
        "y": 10
      },
      "to": {
        "x": 9,
        "y": 0
      },
      "pieceType": "INFILTRATOR"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-h2",
      "from": {
        "x": 8,
        "y": 0
      },
      "to": {
        "x": 8,
        "y": 3
      },
      "pieceType": "BEAM"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-h2",
      "from": {
        "x": 8,
        "y": 10
      },
      "to": {
        "x": 8,
        "y": 7
      },
      "pieceType": "BEAM"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-h1",
      "from": {
        "x": 2,
        "y": 3
      },
      "to": {
        "x": 4,
        "y": 3
      },
      "pieceType": "BEAM"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-h1",
      "from": {
        "x": 2,
        "y": 10
      },
      "to": {
        "x": 2,
        "y": 7
      },
      "pieceType": "BEAM"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-h2",
      "from": {
        "x": 8,
        "y": 3
      },
      "to": {
        "x": 6,
        "y": 3
      },
      "pieceType": "BEAM"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-h2",
      "from": {
        "x": 8,
        "y": 7
      },
      "to": {
        "x": 5,
        "y": 7
      },
      "pieceType": "BEAM"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-e4",
      "from": {
        "x": 5,
        "y": 3
      },
      "to": {
        "x": 5,
        "y": 4
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-h1",
      "from": {
        "x": 2,
        "y": 7
      },
      "to": {
        "x": 4,
        "y": 7
      },
      "pieceType": "BEAM"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-h2",
      "from": {
        "x": 6,
        "y": 3
      },
      "to": {
        "x": 6,
        "y": 5
      },
      "pieceType": "BEAM"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-e2",
      "from": {
        "x": 6,
        "y": 10
      },
      "to": {
        "x": 6,
        "y": 9
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-h1",
      "from": {
        "x": 4,
        "y": 3
      },
      "to": {
        "x": 4,
        "y": 5
      },
      "pieceType": "BEAM"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-i2",
      "from": {
        "x": 9,
        "y": 0
      },
      "to": {
        "x": 4,
        "y": 5
      },
      "pieceType": "INFILTRATOR",
      "captured": "w-h1"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-e1",
      "from": {
        "x": 4,
        "y": 0
      },
      "to": {
        "x": 4,
        "y": 1
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-i2",
      "from": {
        "x": 4,
        "y": 5
      },
      "to": {
        "x": 6,
        "y": 5
      },
      "pieceType": "INFILTRATOR",
      "captured": "w-h2"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-e1",
      "from": {
        "x": 4,
        "y": 1
      },
      "to": {
        "x": 4,
        "y": 2
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-e2",
      "from": {
        "x": 6,
        "y": 9
      },
      "to": {
        "x": 6,
        "y": 8
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-e2",
      "from": {
        "x": 6,
        "y": 0
      },
      "to": {
        "x": 6,
        "y": 1
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-e2",
      "from": {
        "x": 6,
        "y": 8
      },
      "to": {
        "x": 6,
        "y": 7
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-e3",
      "from": {
        "x": 5,
        "y": 1
      },
      "to": {
        "x": 5,
        "y": 2
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-e2",
      "from": {
        "x": 6,
        "y": 7
      },
      "to": {
        "x": 6,
        "y": 6
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-e1",
      "from": {
        "x": 4,
        "y": 2
      },
      "to": {
        "x": 4,
        "y": 3
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-h2",
      "from": {
        "x": 5,
        "y": 7
      },
      "to": {
        "x": 5,
        "y": 6
      },
      "pieceType": "BEAM"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-ch",
      "from": {
        "x": 5,
        "y": 0
      },
      "to": {
        "x": 5,
        "y": 1
      },
      "pieceType": "COMMAND_HUB"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-e3",
      "from": {
        "x": 5,
        "y": 9
      },
      "to": {
        "x": 5,
        "y": 8
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-e3",
      "from": {
        "x": 5,
        "y": 2
      },
      "to": {
        "x": 5,
        "y": 3
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-e3",
      "from": {
        "x": 5,
        "y": 8
      },
      "to": {
        "x": 5,
        "y": 7
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-e1",
      "from": {
        "x": 4,
        "y": 3
      },
      "to": {
        "x": 4,
        "y": 4
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-e1",
      "from": {
        "x": 4,
        "y": 10
      },
      "to": {
        "x": 4,
        "y": 9
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-ch",
      "from": {
        "x": 5,
        "y": 1
      },
      "to": {
        "x": 5,
        "y": 2
      },
      "pieceType": "COMMAND_HUB"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-e1",
      "from": {
        "x": 4,
        "y": 9
      },
      "to": {
        "x": 4,
        "y": 8
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-e1",
      "from": {
        "x": 4,
        "y": 4
      },
      "to": {
        "x": 4,
        "y": 5
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-h1",
      "from": {
        "x": 4,
        "y": 7
      },
      "to": {
        "x": 4,
        "y": 6
      },
      "pieceType": "BEAM"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-e1",
      "from": {
        "x": 4,
        "y": 5
      },
      "to": {
        "x": 4,
        "y": 6
      },
      "pieceType": "ESCORT",
      "captured": "b-h1"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-h2",
      "from": {
        "x": 5,
        "y": 6
      },
      "to": {
        "x": 4,
        "y": 6
      },
      "pieceType": "BEAM",
      "captured": "w-e1"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-e2",
      "from": {
        "x": 6,
        "y": 1
      },
      "to": {
        "x": 6,
        "y": 2
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-ch",
      "from": {
        "x": 5,
        "y": 10
      },
      "to": {
        "x": 5,
        "y": 9
      },
      "pieceType": "COMMAND_HUB"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-e2",
      "from": {
        "x": 6,
        "y": 2
      },
      "to": {
        "x": 6,
        "y": 3
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-e3",
      "from": {
        "x": 5,
        "y": 7
      },
      "to": {
        "x": 5,
        "y": 6
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-e2",
      "from": {
        "x": 6,
        "y": 3
      },
      "to": {
        "x": 6,
        "y": 4
      },
      "pieceType": "ESCORT"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-i2",
      "from": {
        "x": 6,
        "y": 5
      },
      "to": {
        "x": 6,
        "y": 4
      },
      "pieceType": "INFILTRATOR",
      "captured": "w-e2"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-e4",
      "from": {
        "x": 5,
        "y": 4
      },
      "to": {
        "x": 6,
        "y": 4
      },
      "pieceType": "ESCORT",
      "captured": "b-i2"
    },
    {
      "seat": "BLACK",
      "pieceId": "b-ch",
      "from": {
        "x": 5,
        "y": 9
      },
      "to": {
        "x": 5,
        "y": 8
      },
      "pieceType": "COMMAND_HUB"
    },
    {
      "seat": "WHITE",
      "pieceId": "w-e4",
      "from": {
        "x": 6,
        "y": 4
      },
      "to": {
        "x": 6,
        "y": 5
      },
      "pieceType": "ESCORT"
    }
  ]
};

export default replay;
